// NUCC Health Care Provider Taxonomy — a curated, accurately-coded catalogue of
// the specialties used in enrollment. Each entry is { code, label, group }.
// The onboarding specialty picker is a searchable multi-select over this list
// with a manual-entry fallback, so a specialty that isn't here can still be
// captured (as { code: "", label, manual: true }).
//
// Codes are the official 10-character NUCC taxonomy codes. Grouped by NUCC
// "Provider Grouping" so the picker can section them.

export const TAXONOMY = [
  // ── Allopathic & Osteopathic Physicians ──
  { code: "207K00000X", label: "Allergy & Immunology", group: "Physician" },
  { code: "207KA0200X", label: "Allergy & Immunology — Allergy", group: "Physician" },
  { code: "207L00000X", label: "Anesthesiology", group: "Physician" },
  { code: "207LP2900X", label: "Anesthesiology — Pain Medicine", group: "Physician" },
  { code: "207LC0200X", label: "Anesthesiology — Critical Care Medicine", group: "Physician" },
  { code: "208U00000X", label: "Clinical Pharmacology", group: "Physician" },
  { code: "208C00000X", label: "Colon & Rectal Surgery", group: "Physician" },
  { code: "207N00000X", label: "Dermatology", group: "Physician" },
  { code: "207ND0900X", label: "Dermatology — Dermatopathology", group: "Physician" },
  { code: "207NP0225X", label: "Dermatology — Pediatric Dermatology", group: "Physician" },
  { code: "204R00000X", label: "Electrodiagnostic Medicine", group: "Physician" },
  { code: "207P00000X", label: "Emergency Medicine", group: "Physician" },
  { code: "207PE0004X", label: "Emergency Medicine — Emergency Medical Services", group: "Physician" },
  { code: "207PP0204X", label: "Emergency Medicine — Pediatric Emergency Medicine", group: "Physician" },
  { code: "207Q00000X", label: "Family Medicine", group: "Physician" },
  { code: "207QA0000X", label: "Family Medicine — Adolescent Medicine", group: "Physician" },
  { code: "207QG0300X", label: "Family Medicine — Geriatric Medicine", group: "Physician" },
  { code: "207QS0010X", label: "Family Medicine — Sports Medicine", group: "Physician" },
  { code: "208D00000X", label: "General Practice", group: "Physician" },
  { code: "208600000X", label: "Surgery (General Surgery)", group: "Physician" },
  { code: "2086S0120X", label: "Surgery — Plastic & Reconstructive Surgery", group: "Physician" },
  { code: "2086S0122X", label: "Surgery — Surgical Critical Care", group: "Physician" },
  { code: "2086X0206X", label: "Surgery — Surgical Oncology", group: "Physician" },
  { code: "2086S0105X", label: "Surgery — Surgery of the Hand", group: "Physician" },
  { code: "207R00000X", label: "Internal Medicine", group: "Physician" },
  { code: "207RA0000X", label: "Internal Medicine — Adolescent Medicine", group: "Physician" },
  { code: "207RC0000X", label: "Internal Medicine — Cardiovascular Disease", group: "Physician" },
  { code: "207RI0011X", label: "Internal Medicine — Interventional Cardiology", group: "Physician" },
  { code: "207RC0001X", label: "Internal Medicine — Clinical Cardiac Electrophysiology", group: "Physician" },
  { code: "207RE0101X", label: "Internal Medicine — Endocrinology, Diabetes & Metabolism", group: "Physician" },
  { code: "207RG0100X", label: "Internal Medicine — Gastroenterology", group: "Physician" },
  { code: "207RH0000X", label: "Internal Medicine — Hematology", group: "Physician" },
  { code: "207RH0003X", label: "Internal Medicine — Hematology & Oncology", group: "Physician" },
  { code: "207RI0200X", label: "Internal Medicine — Infectious Disease", group: "Physician" },
  { code: "207RG0300X", label: "Internal Medicine — Geriatric Medicine", group: "Physician" },
  { code: "207RN0300X", label: "Internal Medicine — Nephrology", group: "Physician" },
  { code: "207RX0202X", label: "Internal Medicine — Medical Oncology", group: "Physician" },
  { code: "207RP1001X", label: "Internal Medicine — Pulmonary Disease", group: "Physician" },
  { code: "207RR0500X", label: "Internal Medicine — Rheumatology", group: "Physician" },
  { code: "207RC0200X", label: "Internal Medicine — Critical Care Medicine", group: "Physician" },
  { code: "207RS0012X", label: "Internal Medicine — Sleep Medicine", group: "Physician" },
  { code: "208000000X", label: "Pediatrics", group: "Physician" },
  { code: "2080C0008X", label: "Pediatrics — Child Abuse Pediatrics", group: "Physician" },
  { code: "2080P0201X", label: "Pediatrics — Pediatric Cardiology", group: "Physician" },
  { code: "2080P0205X", label: "Pediatrics — Pediatric Critical Care Medicine", group: "Physician" },
  { code: "2080P0206X", label: "Pediatrics — Pediatric Emergency Medicine", group: "Physician" },
  { code: "2080P0207X", label: "Pediatrics — Pediatric Endocrinology", group: "Physician" },
  { code: "2080P0208X", label: "Pediatrics — Pediatric Gastroenterology", group: "Physician" },
  { code: "2080P0210X", label: "Pediatrics — Pediatric Hematology-Oncology", group: "Physician" },
  { code: "2080N0001X", label: "Pediatrics — Neonatal-Perinatal Medicine", group: "Physician" },
  { code: "207V00000X", label: "Obstetrics & Gynecology", group: "Physician" },
  { code: "207VM0101X", label: "Obstetrics & Gynecology — Maternal & Fetal Medicine", group: "Physician" },
  { code: "207VG0400X", label: "Obstetrics & Gynecology — Gynecology", group: "Physician" },
  { code: "207VX0201X", label: "Obstetrics & Gynecology — Gynecologic Oncology", group: "Physician" },
  { code: "207VE0102X", label: "Obstetrics & Gynecology — Reproductive Endocrinology", group: "Physician" },
  { code: "207W00000X", label: "Ophthalmology", group: "Physician" },
  { code: "207WX0009X", label: "Ophthalmology — Glaucoma Specialist", group: "Physician" },
  { code: "207WX0107X", label: "Ophthalmology — Retina Specialist", group: "Physician" },
  { code: "207X00000X", label: "Orthopaedic Surgery", group: "Physician" },
  { code: "207XS0114X", label: "Orthopaedic Surgery — Adult Reconstructive Orthopaedic Surgery", group: "Physician" },
  { code: "207XX0801X", label: "Orthopaedic Surgery — Orthopaedic Surgery of the Spine", group: "Physician" },
  { code: "207XS0117X", label: "Orthopaedic Surgery — Orthopaedic Sports Medicine", group: "Physician" },
  { code: "207XX0004X", label: "Orthopaedic Surgery — Foot & Ankle Surgery", group: "Physician" },
  { code: "207Y00000X", label: "Otolaryngology (ENT)", group: "Physician" },
  { code: "207YS0123X", label: "Otolaryngology — Facial Plastic Surgery", group: "Physician" },
  { code: "207YX0602X", label: "Otolaryngology — Otolaryngic Allergy", group: "Physician" },
  { code: "208VP0014X", label: "Pain Medicine — Interventional Pain Medicine", group: "Physician" },
  { code: "208VP0000X", label: "Pain Medicine", group: "Physician" },
  { code: "207ZP0101X", label: "Pathology — Anatomic Pathology", group: "Physician" },
  { code: "207ZP0102X", label: "Pathology — Anatomic & Clinical Pathology", group: "Physician" },
  { code: "207ZC0500X", label: "Pathology — Clinical Pathology", group: "Physician" },
  { code: "208100000X", label: "Physical Medicine & Rehabilitation", group: "Physician" },
  { code: "2081P2900X", label: "Physical Medicine & Rehabilitation — Pain Medicine", group: "Physician" },
  { code: "2081N0008X", label: "Physical Medicine & Rehabilitation — Neuromuscular Medicine", group: "Physician" },
  { code: "2081S0010X", label: "Physical Medicine & Rehabilitation — Sports Medicine", group: "Physician" },
  { code: "208200000X", label: "Plastic Surgery", group: "Physician" },
  { code: "2082S0099X", label: "Plastic Surgery — Plastic Surgery Within the Head & Neck", group: "Physician" },
  { code: "2082S0105X", label: "Plastic Surgery — Surgery of the Hand", group: "Physician" },
  { code: "2083P0500X", label: "Preventive Medicine — Preventive Medicine/Occupational Environmental Medicine", group: "Physician" },
  { code: "2083P0901X", label: "Preventive Medicine — Public Health & General Preventive Medicine", group: "Physician" },
  { code: "2084P0800X", label: "Psychiatry & Neurology — Psychiatry", group: "Physician" },
  { code: "2084N0400X", label: "Psychiatry & Neurology — Neurology", group: "Physician" },
  { code: "2084P0805X", label: "Psychiatry & Neurology — Geriatric Psychiatry", group: "Physician" },
  { code: "2084P0804X", label: "Psychiatry & Neurology — Child & Adolescent Psychiatry", group: "Physician" },
  { code: "2084A2900X", label: "Psychiatry & Neurology — Addiction Medicine", group: "Physician" },
  { code: "2084P0802X", label: "Psychiatry & Neurology — Addiction Psychiatry", group: "Physician" },
  { code: "2084N0600X", label: "Psychiatry & Neurology — Clinical Neurophysiology", group: "Physician" },
  { code: "2084S0012X", label: "Psychiatry & Neurology — Sleep Medicine", group: "Physician" },
  { code: "2085R0202X", label: "Radiology — Diagnostic Radiology", group: "Physician" },
  { code: "2085R0001X", label: "Radiology — Radiation Oncology", group: "Physician" },
  { code: "2085R0204X", label: "Radiology — Vascular & Interventional Radiology", group: "Physician" },
  { code: "2085N0904X", label: "Radiology — Neuroradiology", group: "Physician" },
  { code: "2085R0203X", label: "Radiology — Therapeutic Radiology", group: "Physician" },
  { code: "208G00000X", label: "Thoracic Surgery (Cardiothoracic Vascular Surgery)", group: "Physician" },
  { code: "2086S0129X", label: "Surgery — Vascular Surgery", group: "Physician" },
  { code: "208800000X", label: "Urology", group: "Physician" },
  { code: "2088P0231X", label: "Urology — Pediatric Urology", group: "Physician" },
  { code: "2088F0040X", label: "Urology — Female Pelvic Medicine & Reconstructive Surgery", group: "Physician" },
  { code: "204D00000X", label: "Neuromusculoskeletal Medicine & OMM", group: "Physician" },
  { code: "204E00000X", label: "Oral & Maxillofacial Surgery", group: "Physician" },
  { code: "2086H0002X", label: "Surgery — Trauma Surgery", group: "Physician" },
  { code: "207T00000X", label: "Neurological Surgery", group: "Physician" },

  // ── Behavioral Health & Social Service ──
  { code: "103T00000X", label: "Psychologist", group: "Behavioral Health" },
  { code: "103TC0700X", label: "Psychologist — Clinical", group: "Behavioral Health" },
  { code: "1041C0700X", label: "Clinical Social Worker (LCSW)", group: "Behavioral Health" },
  { code: "101YM0800X", label: "Counselor — Mental Health", group: "Behavioral Health" },
  { code: "101YA0400X", label: "Counselor — Addiction (Substance Use Disorder)", group: "Behavioral Health" },
  { code: "106H00000X", label: "Marriage & Family Therapist", group: "Behavioral Health" },
  { code: "2084P0800X", label: "Psychiatrist", group: "Behavioral Health" },
  { code: "163WP0808X", label: "Psychiatric/Mental Health Nurse Practitioner", group: "Behavioral Health" },
  { code: "251S00000X", label: "Community/Behavioral Health Agency", group: "Behavioral Health" },

  // ── Nursing & Advanced Practice ──
  { code: "363L00000X", label: "Nurse Practitioner", group: "Advanced Practice" },
  { code: "363LF0000X", label: "Nurse Practitioner — Family", group: "Advanced Practice" },
  { code: "363LA2200X", label: "Nurse Practitioner — Adult Health", group: "Advanced Practice" },
  { code: "363LP2300X", label: "Nurse Practitioner — Primary Care", group: "Advanced Practice" },
  { code: "363LG0600X", label: "Nurse Practitioner — Gerontology", group: "Advanced Practice" },
  { code: "363LP0200X", label: "Nurse Practitioner — Pediatrics", group: "Advanced Practice" },
  { code: "363LW0102X", label: "Nurse Practitioner — Women's Health", group: "Advanced Practice" },
  { code: "363A00000X", label: "Physician Assistant", group: "Advanced Practice" },
  { code: "363AM0700X", label: "Physician Assistant — Medical", group: "Advanced Practice" },
  { code: "363AS0400X", label: "Physician Assistant — Surgical", group: "Advanced Practice" },
  { code: "367500000X", label: "Certified Registered Nurse Anesthetist (CRNA)", group: "Advanced Practice" },
  { code: "367A00000X", label: "Advanced Practice Midwife", group: "Advanced Practice" },
  { code: "163W00000X", label: "Registered Nurse", group: "Advanced Practice" },
  { code: "364S00000X", label: "Clinical Nurse Specialist", group: "Advanced Practice" },

  // ── Dental ──
  { code: "122300000X", label: "Dentist", group: "Dental" },
  { code: "1223G0001X", label: "Dentist — General Practice", group: "Dental" },
  { code: "1223S0112X", label: "Dentist — Oral & Maxillofacial Surgery", group: "Dental" },
  { code: "1223X0400X", label: "Dentist — Orthodontics", group: "Dental" },
  { code: "1223P0221X", label: "Dentist — Pediatric Dentistry", group: "Dental" },
  { code: "1223E0200X", label: "Dentist — Endodontics", group: "Dental" },
  { code: "1223P0300X", label: "Dentist — Periodontics", group: "Dental" },
  { code: "1223P0700X", label: "Dentist — Prosthodontics", group: "Dental" },

  // ── Podiatry, Eye, Chiropractic ──
  { code: "213E00000X", label: "Podiatrist", group: "Foot / Eye / Chiropractic" },
  { code: "213ES0103X", label: "Podiatrist — Foot & Ankle Surgery", group: "Foot / Eye / Chiropractic" },
  { code: "152W00000X", label: "Optometrist", group: "Foot / Eye / Chiropractic" },
  { code: "111N00000X", label: "Chiropractor", group: "Foot / Eye / Chiropractic" },

  // ── Therapy & Rehabilitation ──
  { code: "225100000X", label: "Physical Therapist", group: "Therapy & Rehab" },
  { code: "225X00000X", label: "Occupational Therapist", group: "Therapy & Rehab" },
  { code: "235Z00000X", label: "Speech-Language Pathologist", group: "Therapy & Rehab" },
  { code: "231H00000X", label: "Audiologist", group: "Therapy & Rehab" },
  { code: "224Z00000X", label: "Occupational Therapy Assistant", group: "Therapy & Rehab" },
  { code: "225200000X", label: "Physical Therapy Assistant", group: "Therapy & Rehab" },
  { code: "224P00000X", label: "Respiratory Therapist", group: "Therapy & Rehab" },

  // ── Facilities & Organizations (Type 2) ──
  { code: "261Q00000X", label: "Clinic/Center", group: "Facility / Organization" },
  { code: "261QP2300X", label: "Clinic/Center — Primary Care", group: "Facility / Organization" },
  { code: "261QM0850X", label: "Clinic/Center — Adult Mental Health", group: "Facility / Organization" },
  { code: "261QU0200X", label: "Clinic/Center — Urgent Care", group: "Facility / Organization" },
  { code: "261QR0200X", label: "Clinic/Center — Radiology", group: "Facility / Organization" },
  { code: "261QA1903X", label: "Clinic/Center — Ambulatory Surgical", group: "Facility / Organization" },
  { code: "282N00000X", label: "General Acute Care Hospital", group: "Facility / Organization" },
  { code: "314000000X", label: "Skilled Nursing Facility", group: "Facility / Organization" },
  { code: "251G00000X", label: "Hospice Care, Community Based", group: "Facility / Organization" },
  { code: "251E00000X", label: "Home Health Agency", group: "Facility / Organization" },
  { code: "3336C0003X", label: "Pharmacy — Community/Retail", group: "Facility / Organization" },
  { code: "291U00000X", label: "Clinical Medical Laboratory", group: "Facility / Organization" },
  { code: "335E00000X", label: "Durable Medical Equipment & Medical Supplies", group: "Facility / Organization" },
  { code: "333600000X", label: "Pharmacy", group: "Facility / Organization" },

  // ── Other Practitioners ──
  { code: "171100000X", label: "Acupuncturist", group: "Other" },
  { code: "133V00000X", label: "Dietitian, Registered", group: "Other" },
  { code: "175F00000X", label: "Naturopath", group: "Other" },
  { code: "146L00000X", label: "Paramedic (EMT)", group: "Other" },
  { code: "225700000X", label: "Massage Therapist", group: "Other" },
];

// Distinct groups, in a stable display order.
export const TAXONOMY_GROUPS = [
  "Physician",
  "Advanced Practice",
  "Behavioral Health",
  "Dental",
  "Foot / Eye / Chiropractic",
  "Therapy & Rehab",
  "Facility / Organization",
  "Other",
];

export function findTaxonomy(code) {
  return TAXONOMY.find((t) => t.code === code) || null;
}
